### ISSUE TITLE
ENSPY AI Meeting: Sharing Ideas with Willwabo

### ISSUE THREAD

**Issue by nprime496** [ENSP-AI-Mentoring/UbuntU#41]
Hello @WILLWABO ,

We're pleased to announce that you've been selected for an exciting opportunity within our community! As a valued member, we invite you to share your expertise by hosting a meeting on a topic of interest.

Please let us know your response, indicating whether you are available and your topic of choice you'd like to share with us. We will respond to validate needed details. We are eagerly looking forward to your participation and the unique insights you will contribute to our community.

Thank you for being a vital part of our community's journey.

For more information about our selection process, please take a look at [this article](https://medium.com/@1001pepi/random-selection-of-members-for-activities-planning-7b373743d4fb).

Best Regards,

[@ENSPY_AI](https://github.com/ENSP-AI-Mentoring)

**Comment by WILLWABO** [comment]
Thank you for the invitation,

I will make a presentation on the 16th March 2024 on the topic of Q* in LLMs

**Comment by nprime496** [comment]
Hi Will,

As I told you, you can do a presentation on reinforcement learning instead, as it was your initial choice.

Are you still interested by Q* ?

**Comment by WILLWABO** [comment]
I'll make a presentation on reinforcement learning instead

**Comment by KameniAlexNea** [comment]
Can you please share with us the paper on which you're preparing your presentation ?
